### ISSUE TITLE
jquery-pjax is unmaintained

### ISSUE THREAD

**Issue by armpogart** [yiisoft/jquery-pjax#53]
As far as I know jquery-pjax (original one, from which this one is forked) is now unmaintained and it has many porblems (especially the one that it's not working with jQuery 3+ and has some serious problems in IOS 10).

So maybe it's time to migrate yii to alternatives:
- https://github.com/turbolinks/turbolinks
- https://github.com/LeadDyno/intercooler-js

**Comment by samdark** [comment]
Yes, we were thinking about that and indeed there are too many problems with PJAX. In 2.1 we are going to drop support for it from the core framework. I'm not sure yet if any other alike solution will be adopted.

In 2.0 we have to support it because it's not a good idea to suddenly break things which work.

**Comment by dynasource** [comment]
thanks for your sharing your suggestions. We are familiar with those tools and they are good for the functionality they offer. 

What we've learned from the past is that integrating 3rd party software is quite maintenance heavy. With respect to this concern, we are thinking twice before doing that. Especially with respect to this type of architecture in which client & serverside have to communicate. 

However, we've seen its popularity in the Community. Not for the least for the hundreds open tickets we have had about it. It is a useful and powerful technology. Perhabs I am thinking about developing a solution myself in 2017. Keep an eye out for that.
